version: '2'
services:
  ofv-app:
    image: ofv
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://ofv-mariadb:3306/ofv
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  ofv-mariadb:
    extends:
      file: mariadb.yml
      service: ofv-mariadb
